%YAML:1.0
---
calibration_time: "Wed Nov 11 20:55:49 2020"
image_width: 1080
image_height: 720
board_width: 9
board_height: 6
square_size: 1.
aspectRatio: 1.
flags: 2
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 638.94033, 0., 321.54076, 0.,
       637.11566, 229.44901, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ 0.056010, -0.127288,
      -0.000571,  0.000208,
       0.0 ]
avg_reprojection_error: 0.0371185753469972

# источник изображения
video_source: 0
# положение камеры в связной СК
camera_X: 0 
camera_Y: 0
camera_Z: 0
camera_roll: 0
camera_pitch: 0
camera_yaw: 0
