%YAML:1.0
---
calibration_time: "Wed Nov 11 20:55:49 2020"
image_width: 800
image_height: 800
board_width: 9
board_height: 6
square_size: 0.11
aspectRatio: 1.
flags: 2
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 478.10341, 0., 398.01, 0.,
       478.27375, 400.46145, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ 0. , 0.,
      0., 0.,
       0.0 ]
avg_reprojection_error: 0.0371185753469972

# источник изображения
video_source: -1
# положение камеры в связной СК
camera_X: 0 
camera_Y: 0
camera_Z: -0.03
camera_roll: 0
camera_pitch: 0
camera_yaw: 1.57
