%YAML:1.0
---
calibration_time: "Wed Nov 11 20:55:49 2020"
image_width: 1280
image_height: 960
board_width: 9
board_height: 6
square_size: 1.
aspectRatio: 1.
flags: 2
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 770.65528, 0., 642.2207, 0.,
       763.50104, 453.53393, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -0.309270, 0.085000,
      0.001216,  0.000686,
       0.0 ]
avg_reprojection_error: 0.0371185753469972

# источник изображения
video_source: 4
# положение камеры в связной СК
camera_X: 0 
camera_Y: 0
camera_Z: 0
camera_roll: 0
camera_pitch: 0
camera_yaw: 0
