%YAML:1.0
---
# указываем типы используемых словарей
# (количесво квадратиков внутри маркера определяющих его сигнатуру)
# 4 - размерность бинарной матрицы маркера 4 x 4 
# 5 - размерность бинарной матрицы маркера 5 x 5
# 6 - размерность бинарной матрицы маркера 6 x 6
# 7 - размерность бинарной матрицы маркера 7 x 7
marker_dictionaries_type: [4,5,6,7]
#размер загружаемого словаря (возможны варианты 50 100 250 1000)
# этот параметр определяет используемый набор маркеров 
# чем больше размер словаря тем болше различных маркеров можно использовать для построения навигационного поля
# однако чем больше размер словаря тем дольше работает система ведь для каждого обнаруженного маркера необходимо выполнить проверку
# на соответствие тому или иному маркеру в словаре 
dictionaries_sizes: [100,100,100,100]