%YAML:1.0

---

#размерность маркера по битам (возможны варианты 4 5 6 7)
marker_bit_sizes: [4,7]

#размер загружаемого словаря (возможны варианты 50 100 250 1000)
dict_sizes: [50,100]

marker_count: 3 #количество маркеров в поле

dict_count: 2

#marker_bit_size -0
#id -1
#x -2
#y -3
#z -4
#roll -5
#pith -6
#yaw -7
#размер маркера в метрах - 8

marker_1: [4,0,0,0,0,0,0,0,0.4]

marker_2: [4,2,1,0,0,0,0,0,0.2]

marker_3: [7,10,0,0.3,0,0,0,0,0.5]
