marker_count: 1 #количество маркеров в карте
wait_time_before_marker_add: 10


# A4 markers size
#marker_size: 0.190

# mini board marker size
# marker_size: 0.041 

# gazebo sim marker
marker_size: 0.951240 
# marker_size: 1 

axes_size: 0.5


# marker_size_groups: [] 
# marker_ids_group_1: []
#marker_bit_size - 0
#id -1
#x -2
#y -3
#z -4
#roll -5 поворот вокруг оси Y
#pith -6 поворот вокруг оси X
#yaw -7 поворот вокруг оси Z
#размер маркера в метрах - 8
marker_1: [4,0,0,0,0,0,0,0,0.951240] # для работы SLAM требуется задать хотя бы один базисный репер
