%YAML:1.0

---

#размерность маркера по битам (возможны варианты 4 5 6 7)
marker_bit_size: 4

#размер загружаемого словаря (возможны варианты 50 100 250 1000)
marker_dict: 50

#номер используемого маркера в словаре от 0 до marker_dict - 1
marker_id: 0

#размер маркера задается в метрах
marker_size: 1

